name: Worker CI
on:
  push:
    branches:
      - master
    paths:
      - worker/**
  pull_request:
    branches:
      - master
    paths:
      - worker/**
jobs:
  ci:
    name: Integration Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./worker
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: python -c "import sys; print(sys.version)"
      - run: pip install -r requirements.txt
      - run: |
         pip install pylint
         pylint worker.py pipeline/...
